//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAPS2.Lang.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SettingsResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SettingsResources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NAPS2.Lang.Resources.SettingsResources", typeof(SettingsResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Black &amp; White.
        /// </summary>
        internal static string BitDepth_1BlackAndWhite {
            get {
                return ResourceManager.GetString("BitDepth_1BlackAndWhite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 24-bit Color.
        /// </summary>
        internal static string BitDepth_24Color {
            get {
                return ResourceManager.GetString("BitDepth_24Color", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Grayscale.
        /// </summary>
        internal static string BitDepth_8Grayscale {
            get {
                return ResourceManager.GetString("BitDepth_8Grayscale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 100 dpi.
        /// </summary>
        internal static string Dpi_100 {
            get {
                return ResourceManager.GetString("Dpi_100", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1200 dpi.
        /// </summary>
        internal static string Dpi_1200 {
            get {
                return ResourceManager.GetString("Dpi_1200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 150 dpi.
        /// </summary>
        internal static string Dpi_150 {
            get {
                return ResourceManager.GetString("Dpi_150", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 200 dpi.
        /// </summary>
        internal static string Dpi_200 {
            get {
                return ResourceManager.GetString("Dpi_200", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 300 dpi.
        /// </summary>
        internal static string Dpi_300 {
            get {
                return ResourceManager.GetString("Dpi_300", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 400 dpi.
        /// </summary>
        internal static string Dpi_400 {
            get {
                return ResourceManager.GetString("Dpi_400", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 600 dpi.
        /// </summary>
        internal static string Dpi_600 {
            get {
                return ResourceManager.GetString("Dpi_600", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 800 dpi.
        /// </summary>
        internal static string Dpi_800 {
            get {
                return ResourceManager.GetString("Dpi_800", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à No provider selected..
        /// </summary>
        internal static string EmailProvider_NotSelected {
            get {
                return ResourceManager.GetString("EmailProvider_NotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Custom SMTP.
        /// </summary>
        internal static string EmailProviderType_CustomSmtp {
            get {
                return ResourceManager.GetString("EmailProviderType_CustomSmtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Gmail.
        /// </summary>
        internal static string EmailProviderType_Gmail {
            get {
                return ResourceManager.GetString("EmailProviderType_Gmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Outlook Web Access.
        /// </summary>
        internal static string EmailProviderType_OutlookWeb {
            get {
                return ResourceManager.GetString("EmailProviderType_OutlookWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Center.
        /// </summary>
        internal static string HorizontalAlign_Center {
            get {
                return ResourceManager.GetString("HorizontalAlign_Center", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Left.
        /// </summary>
        internal static string HorizontalAlign_Left {
            get {
                return ResourceManager.GetString("HorizontalAlign_Left", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right.
        /// </summary>
        internal static string HorizontalAlign_Right {
            get {
                return ResourceManager.GetString("HorizontalAlign_Right", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A3 (297x420 mm).
        /// </summary>
        internal static string PageSize_A3 {
            get {
                return ResourceManager.GetString("PageSize_A3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A4 (210x297 mm).
        /// </summary>
        internal static string PageSize_A4 {
            get {
                return ResourceManager.GetString("PageSize_A4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A5 (148x210 mm).
        /// </summary>
        internal static string PageSize_A5 {
            get {
                return ResourceManager.GetString("PageSize_A5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à B4 (250x353 mm).
        /// </summary>
        internal static string PageSize_B4 {
            get {
                return ResourceManager.GetString("PageSize_B4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à B5 (176x250 mm).
        /// </summary>
        internal static string PageSize_B5 {
            get {
                return ResourceManager.GetString("PageSize_B5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Custom....
        /// </summary>
        internal static string PageSize_Custom {
            get {
                return ResourceManager.GetString("PageSize_Custom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à US Legal (8.5x14 in).
        /// </summary>
        internal static string PageSize_Legal {
            get {
                return ResourceManager.GetString("PageSize_Legal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à US Letter (8.5x11 in).
        /// </summary>
        internal static string PageSize_Letter {
            get {
                return ResourceManager.GetString("PageSize_Letter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à cm.
        /// </summary>
        internal static string PageSizeUnit_Centimetre {
            get {
                return ResourceManager.GetString("PageSizeUnit_Centimetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à in.
        /// </summary>
        internal static string PageSizeUnit_Inch {
            get {
                return ResourceManager.GetString("PageSizeUnit_Inch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à mm.
        /// </summary>
        internal static string PageSizeUnit_Millimetre {
            get {
                return ResourceManager.GetString("PageSizeUnit_Millimetre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default.
        /// </summary>
        internal static string PdfCompat_Default {
            get {
                return ResourceManager.GetString("PdfCompat_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PDF/A-1b.
        /// </summary>
        internal static string PdfCompat_PdfA1B {
            get {
                return ResourceManager.GetString("PdfCompat_PdfA1B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PDF/A-2b.
        /// </summary>
        internal static string PdfCompat_PdfA2B {
            get {
                return ResourceManager.GetString("PdfCompat_PdfA2B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PDF/A-3b.
        /// </summary>
        internal static string PdfCompat_PdfA3B {
            get {
                return ResourceManager.GetString("PdfCompat_PdfA3B", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à PDF/A-3u.
        /// </summary>
        internal static string PdfCompat_PdfA3U {
            get {
                return ResourceManager.GetString("PdfCompat_PdfA3U", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1:1.
        /// </summary>
        internal static string Scale_1_1 {
            get {
                return ResourceManager.GetString("Scale_1_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1:2.
        /// </summary>
        internal static string Scale_1_2 {
            get {
                return ResourceManager.GetString("Scale_1_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1:4.
        /// </summary>
        internal static string Scale_1_4 {
            get {
                return ResourceManager.GetString("Scale_1_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1:8.
        /// </summary>
        internal static string Scale_1_8 {
            get {
                return ResourceManager.GetString("Scale_1_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Duplex.
        /// </summary>
        internal static string Source_Duplex {
            get {
                return ResourceManager.GetString("Source_Duplex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Feeder.
        /// </summary>
        internal static string Source_Feeder {
            get {
                return ResourceManager.GetString("Source_Feeder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Glass.
        /// </summary>
        internal static string Source_Glass {
            get {
                return ResourceManager.GetString("Source_Glass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Auto.
        /// </summary>
        internal static string TiffComp_Auto {
            get {
                return ResourceManager.GetString("TiffComp_Auto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à CCITT4.
        /// </summary>
        internal static string TiffComp_Ccitt4 {
            get {
                return ResourceManager.GetString("TiffComp_Ccitt4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à LZW.
        /// </summary>
        internal static string TiffComp_Lzw {
            get {
                return ResourceManager.GetString("TiffComp_Lzw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        internal static string TiffComp_None {
            get {
                return ResourceManager.GetString("TiffComp_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default.
        /// </summary>
        internal static string TwainImpl_Default {
            get {
                return ResourceManager.GetString("TwainImpl_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Legacy (native UI only).
        /// </summary>
        internal static string TwainImpl_Legacy {
            get {
                return ResourceManager.GetString("TwainImpl_Legacy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Alternative Transfer.
        /// </summary>
        internal static string TwainImpl_MemXfer {
            get {
                return ResourceManager.GetString("TwainImpl_MemXfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Old DSM.
        /// </summary>
        internal static string TwainImpl_OldDsm {
            get {
                return ResourceManager.GetString("TwainImpl_OldDsm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à x64.
        /// </summary>
        internal static string TwainImpl_X64 {
            get {
                return ResourceManager.GetString("TwainImpl_X64", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default.
        /// </summary>
        internal static string WiaVersion_Default {
            get {
                return ResourceManager.GetString("WiaVersion_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 1.0.
        /// </summary>
        internal static string WiaVersion_Wia10 {
            get {
                return ResourceManager.GetString("WiaVersion_Wia10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 2.0.
        /// </summary>
        internal static string WiaVersion_Wia20 {
            get {
                return ResourceManager.GetString("WiaVersion_Wia20", resourceCulture);
            }
        }
    }
}
