//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NAPS2.Lang {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class LanguageNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LanguageNames() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("NAPS2.Lang.LanguageNames", typeof(LanguageNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Afrikaans.
        /// </summary>
        internal static string af {
            get {
                return ResourceManager.GetString("af", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à العَرَبِية.
        /// </summary>
        internal static string ar {
            get {
                return ResourceManager.GetString("ar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à български.
        /// </summary>
        internal static string bg {
            get {
                return ResourceManager.GetString("bg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Català.
        /// </summary>
        internal static string ca {
            get {
                return ResourceManager.GetString("ca", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Čeština.
        /// </summary>
        internal static string cs {
            get {
                return ResourceManager.GetString("cs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Dansk.
        /// </summary>
        internal static string da {
            get {
                return ResourceManager.GetString("da", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deutsch.
        /// </summary>
        internal static string de {
            get {
                return ResourceManager.GetString("de", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Ελληνικά.
        /// </summary>
        internal static string el {
            get {
                return ResourceManager.GetString("el", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à English.
        /// </summary>
        internal static string en {
            get {
                return ResourceManager.GetString("en", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Español.
        /// </summary>
        internal static string es {
            get {
                return ResourceManager.GetString("es", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Eesti keel.
        /// </summary>
        internal static string et {
            get {
                return ResourceManager.GetString("et", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à فارسى.
        /// </summary>
        internal static string fa {
            get {
                return ResourceManager.GetString("fa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Suomi.
        /// </summary>
        internal static string fi {
            get {
                return ResourceManager.GetString("fi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Français.
        /// </summary>
        internal static string fr {
            get {
                return ResourceManager.GetString("fr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à עברית.
        /// </summary>
        internal static string he {
            get {
                return ResourceManager.GetString("he", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à हिन्दी.
        /// </summary>
        internal static string hi {
            get {
                return ResourceManager.GetString("hi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Hrvatski.
        /// </summary>
        internal static string hr {
            get {
                return ResourceManager.GetString("hr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Magyar.
        /// </summary>
        internal static string hu {
            get {
                return ResourceManager.GetString("hu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Italiano.
        /// </summary>
        internal static string it {
            get {
                return ResourceManager.GetString("it", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 日本語.
        /// </summary>
        internal static string ja {
            get {
                return ResourceManager.GetString("ja", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 한국어.
        /// </summary>
        internal static string ko {
            get {
                return ResourceManager.GetString("ko", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Lietuvių kalba.
        /// </summary>
        internal static string lt {
            get {
                return ResourceManager.GetString("lt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Latviešu valoda.
        /// </summary>
        internal static string lv {
            get {
                return ResourceManager.GetString("lv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Bokmål.
        /// </summary>
        internal static string nb {
            get {
                return ResourceManager.GetString("nb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nederlands.
        /// </summary>
        internal static string nl {
            get {
                return ResourceManager.GetString("nl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Nynorsk.
        /// </summary>
        internal static string nn {
            get {
                return ResourceManager.GetString("nn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Polski.
        /// </summary>
        internal static string pl {
            get {
                return ResourceManager.GetString("pl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Português (Brasil).
        /// </summary>
        internal static string pt_BR {
            get {
                return ResourceManager.GetString("pt_BR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Português (Portugal).
        /// </summary>
        internal static string pt_PT {
            get {
                return ResourceManager.GetString("pt_PT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Limba Română.
        /// </summary>
        internal static string ro {
            get {
                return ResourceManager.GetString("ro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Русский язык.
        /// </summary>
        internal static string ru {
            get {
                return ResourceManager.GetString("ru", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à සිංහල.
        /// </summary>
        internal static string si {
            get {
                return ResourceManager.GetString("si", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Slovenčina.
        /// </summary>
        internal static string sk {
            get {
                return ResourceManager.GetString("sk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Slovenščina.
        /// </summary>
        internal static string sl {
            get {
                return ResourceManager.GetString("sl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shqip.
        /// </summary>
        internal static string sq {
            get {
                return ResourceManager.GetString("sq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Српски.
        /// </summary>
        internal static string sr_Cyrl {
            get {
                return ResourceManager.GetString("sr_Cyrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Srpski.
        /// </summary>
        internal static string sr_Latn {
            get {
                return ResourceManager.GetString("sr_Latn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Svenska.
        /// </summary>
        internal static string sv {
            get {
                return ResourceManager.GetString("sv", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Türkçe.
        /// </summary>
        internal static string tr {
            get {
                return ResourceManager.GetString("tr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Українська.
        /// </summary>
        internal static string uk {
            get {
                return ResourceManager.GetString("uk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Tiếng việt.
        /// </summary>
        internal static string vi {
            get {
                return ResourceManager.GetString("vi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à 台語 台灣話.
        /// </summary>
        internal static string zh_TW {
            get {
                return ResourceManager.GetString("zh_TW", resourceCulture);
            }
        }
    }
}
